### PR TITLE
Making Compass working with VL 1.0.8

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by yhoonkim** [comment]
Now it's working well. But still there is a error when building.
```
$ npm run build

> viscompass@0.7.0 build /Users/younghoonkim/Desktop/dev/compass-master
> tsc && browserify src/cp.js -d -s cp | exorcist compass.js.map > compass.js

Error: Cannot find module 'browserify-shim' from '/Users/younghoonkim/Desktop/dev/compass-master/node_modules/vega-lite'
    at /Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/younghoonkim/Desktop/dev/compass-master/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.

> viscompass@0.7.0 postbuild /Users/younghoonkim/Desktop/dev/compass-master
> uglifyjs compass.js -cm --source-map compass.min.js.map > compass.min.js
```
